Signin page
alexawesomecode/html-form-project pull request #1
Opened 2019-09-23 21:10 UTC by shemaeric

### What does this Pull Request do?

This Pull request applies all the functionalities of the `HTML FORM project`.

2019-09-23 23:31 UTC, stratospherique reviewed
### Pull request under review by Ahmed Mahfoudh TSE

2019-09-23 23:43 UTC, stratospherique requested changes
### Great work team :clap: . However, you need to implement some requirements in order for us to approve your project. check below :arrow_down: 

#### Page structure

##### Sign In Button

* [ ] It has a Sign In button at the top right corner.

##### Intuit products

* [ ] The products row is under the Intuit logo and above the form.
* [x] It shows the Mint logo and text (logo on the left, text on the right).
* [ ] It shows the Quickbooks logo and text (logo on the left, text on the right).
* [ ] It shows the Turbotax logo and text (logo on the left, text on the right).

##### Form

###### Create account button

- **[REQUIRED]** add an attribute `type="submit"` to your button :nerd_face: 

### General requirements

- **[REQUIRED]** Your linter checker is not properly configured. Did you check [Microverse's guide](https://github.com/microverseinc/linters-config/tree/master/css) ? Please do and follow the instruction :small_airplane: 

### That's it :relieved: . When finished, kindly resubmit another code review request :pray: .

2019-09-24 20:24 UTC, shemaeric commented
> ### Great work team 👏 . However, you need to implement some requirements in order for us to approve your project. check below ⬇️
> #### Page structure
> ##### Sign In Button
> * [ ]  It has a Sign In button at the top right corner.
> 
> ##### Intuit products
> * [ ]  The products row is under the Intuit logo and above the form.
> * [x]  It shows the Mint logo and text (logo on the left, text on the right).
> * [ ]  It shows the Quickbooks logo and text (logo on the left, text on the right).
> * [ ]  It shows the Turbotax logo and text (logo on the left, text on the right).
> 
> ##### Form
> ###### Create account button
> * **[REQUIRED]** add an attribute `type="submit"` to your button 🤓
> 
> ### General requirements
> * **[REQUIRED]** Your linter checker is not properly configured. Did you check [Microverse's guide](https://github.com/microverseinc/linters-config/tree/master/css) ? Please do and follow the instruction 🛩
> 
> ### That's it 😌 . When finished, kindly resubmit another code review request 🙏 .

Thank you @stratospherique for the review. We have applied all the requested changes, you can look at it again.

2019-10-02 16:06 UTC, whiz25 commented on index.html
> +            <button name="create"><span class="custom-span"></span> Create Account</button>
please change this to ```<input type='submit' value='Create Account>```. this was already pointed out by the previous reviewer. make only this one change and this project will get approved.

2019-10-02 16:07 UTC, whiz25 requested changes
## Good job :+1: 
Check my comment and make that change and re-submit.

2019-10-02 22:10 UTC, stratospherique approved these changes
### Great work implementing the suggested changes :clap: . Your project is approved :heavy_check_mark:  and you may merge to master :+1: :+1: :+1:

2019-10-02 22:50 UTC, merged